services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: avito_merch_db
      POSTGRES_HOST: db
    ports:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - .:/code
    ports:
      - "8080:8080"
      - "8089:8089"
    depends_on:
      - db

volumes:
  pg_data:
